const Homeproduct = 
[
    {
        id : 1,
        Name : 'Product1',
        price : '25,000',
        image : 'images/product1.jpg',
        cat : '',
        type : 'new',
    },
    {
        id : 2,
        Name : 'Product2',
        price : '30,000',
        image : 'images/product2.jpg',
        cat : '',
        type : 'featured',
    },
    {
        id : 3,
        Name : 'Product3',
        price : '40,000',
        image : 'images/product3.jpg',
        cat : '',
        type : 'top',
    },
    {
        id : 4,
        Name : 'Product4',
        price : '2,000',
        image : 'images/product4.jpg',
        cat : '',
        type : 'new',
    },
    {
        id : 5,
        Name : 'Product5',
        price : '2,500',
        image : 'images/product5.jpg',
        cat : '',
        type : 'featured',
    },
    {
        id : 6,
        Name : 'Product6',
        price : '1,000',
        image : 'images/product6.jpg',
        cat : '',
        type : 'top',
    },
    {
        id : 7,
        Name : 'Product7',
        price : '40,000',
        image : 'images/product7.jpg',
        cat : '',
        type : 'new',
    },
    {
        id : 8,
        Name : 'Product8',
        price : '35,000',
        image : 'images/product8.jpg',
        cat : '',
        type : 'featured',
    },
    {
        id : 9,
        Name : 'Product9',
        price : '35,000',
        image : 'images/product9.jpg',
        cat : '',
        type : 'top',
    },
    {
        id : 10,
        Name : 'Product10',
        price : '35,000',
        image : 'images/product10.jpg',
        cat : '',
        type : 'new',
    },
    {
        id : 11,
        Name : 'Product11',
        price : '35,000',
        image : 'images/product11.jpg',
        cat : '',
        type : 'featured',
    },
    {
        id : 12,
        Name : 'Product12',
        price : '35,000',
        image : 'images/product12.jpg',
        cat : '',
        type : 'top',
    },
]


export default Homeproduct