const Homeproduct = [
  {
    id: 1,
    Name: "Product1",
    price: "25000",
    image: "../ecommerce-gym-website/images//product1.jpg",
    cat: "threadmill",
    type: "new",
  },
  {
    id: 2,
    Name: "Product2",
    price: "23000",
    image: "../ecommerce-gym-website/images//product2.jpg",
    cat: "threadmill",
    type: "featured",
  },
  {
    id: 3,
    Name: "Product3",
    price: "10000",
    image: "../ecommerce-gym-website/images//product3.jpg",
    cat: "threadmill",
    type: "top",
  },
  {
    id: 4,
    Name: "Product4",
    price: "2000",
    image: "../ecommerce-gym-website/images//product4.jpg",
    cat: "dumbell",
    type: "new",
  },
  {
    id: 5,
    Name: "Product5",
    price: "2500",
    image: "../ecommerce-gym-website/images//product5.jpg",
    cat: "dumbell",
    type: "featured",
  },
  {
    id: 6,
    Name: "Product6",
    price: "1000",
    image: "../ecommerce-gym-website/images//product6.jpg",
    cat: "dumbell",
    type: "top",
  },
  {
    id: 7,
    Name: "Product7",
    price: "20000",
    image: "../ecommerce-gym-website/images//product7.jpg",
    cat: "cardio",
    type: "new",
  },
  {
    id: 8,
    Name: "Product8",
    price: "35000",
    image: "../ecommerce-gym-website/images//product8.jpg",
    cat: "cardio",
    type: "featured",
  },
  {
    id: 9,
    Name: "Product9",
    price: "20000",
    image: "../ecommerce-gym-website/images//product9.jpg",
    cat: "cardio",
    type: "top",
  },
  {
    id: 10,
    Name: "Product10",
    price: "15000",
    image: "../ecommerce-gym-website/images//product10.jpg",
    cat: "dumbell",
    type: "new",
  },
  {
    id: 11,
    Name: "Product11",
    price: "28000",
    image: "../ecommerce-gym-website/images//product11.jpg",
    cat: "dumbell",
    type: "featured",
  },
  {
    id: 12,
    Name: "Product12",
    price: "25000",
    image: "../ecommerce-gym-website/images//product12.jpg",
    cat: "cardio",
    type: "top",
  },
];

export default Homeproduct;
